### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by Mihailoff** [dreamyguy/gitlogg#4] opened 2016-06-07 09:00 UTC
Hello, I'm trying to follow simple mode and generate something

```
git checkout v0.1.4
./gitlogg.sh
```

`Generating git log for all repositories located at '../repos/*/'. This might take a while!
The file ./gitlogg.tmp generated in: 1s
Error: Couldn't find preset "es2015" relative to directory "/Users/user/folder/gitlogg"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:140:24)`

`node -v
v4.4.3`

`OSX 10.11.5`

**Comment by dreamyguy** [comment] 2016-06-07 10:26
Hi @Mihailoff I haven't tried to reproduce your error but it looks like you're missing one or more of the [requirements](https://github.com/dreamyguy/gitlogg#requirements).

If you run `npm install` you're supposed to get the `es2015` preset from [here](https://github.com/dreamyguy/gitlogg/blob/v0.1.4/package.json#L26).

Also don't forget to install **babel-cli** globally by running `npm install babel-cli -g`

**Comment by dreamyguy** [comment] 2016-06-07 16:14
OK, I've reproduced and resolved your error by doing the following steps:
- `nvm install v4.4.3` - which both installed and activated the **node** version you're using.
- Clone the repo on `<new-folder>`. I did it on `Desktop`.
- Given you're on `<new-folder>`, `cd gitlogg/gitlogg/`
- `./gitlogg.sh`
- Error: `gitlogg-generate-log.sh: line 56: babel: command not found`
- Install `npm install babel-cli -g` (to make it available globally in the newly installed `node` version)
- `./gitlogg.sh`
- `Error: Couldn't find preset "es2015" relative to directory "/Users/Wallace/Desktop/gitlogg"`

That's the state you're in. To resolve the error, make sure you're at the repo's root. From my current location, I did:
- `cd ../`
- `npm install`
- `cd gitlogg/`
- `./gitlogg.sh`
- Profit! ✨ 

I'm taking the liberty to close the issue, since the solution is written above. As stated, what you need is to run `npm install` at the root of your clone/fork, `cd` to _gitlogg_ folder and run the shell script again. 😉

**Closed as completed by dreamyguy** 2016-06-07 16:14 UTC

**Comment by Mihailoff** [comment] 2016-06-08 17:42
Thank you, looks like I've missed 3rd step from https://github.com/dreamyguy/gitlogg#requirements

Now works.

**Comment by dreamyguy** [comment] 2016-06-08 18:57
I'm glad to hear that @Mihailoff, have fun!
